### ISSUE TITLE
Exception in IntelliJ 2023.1

### ISSUE THREAD

**Issue by DAmNRelentless** [LabyStudio/singlehotswap#9]
The built-in single hotswap button that's inside the redesigned run widget throws an exception. I am using the new UI.

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 205,4,main] 29799535 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1827067947
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:133)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:125)
	at net.labymod.intellij.singlehotswap.compiler.impl.BuiltInJavaCompiler.compile(BuiltInJavaCompiler.java:43)
	at net.labymod.intellij.singlehotswap.actions.SingleHotswapAction.lambda$actionPerformed$0(SingleHotswapAction.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at net.labymod.intellij.singlehotswap.actions.SingleHotswapAction.lambda$actionPerformed$1(SingleHotswapAction.java:139)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    debugger.mayBringFrameToFrontOnBreakpoint=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=15

Non-Bundled Plugins:
    com.intellij.plugins.vscodekeymap (231.8109.91)
    color.scheme.Relentless-Colors (1.2.4)
    com.samdark.intellij-visual-studio-code-dark-plus (2.6)
    com.github.copilot (1.2.5.2507)
    org.jetbrains.jumpToLine (0.1.13)
    com.mallowigi (88.0.0)
    com.dsoftware.ghtoolbar (1.10.3)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.chylex.intellij.inspectionlens (1.1.1)
    mobi.hsz.idea.gitignore (4.5.0)
    com.nasller.CodeGlancePro (1.6.0-2023.1)
    com.demonwav.minecraft-dev (2023.1-1.6.3)
    net.labymod.intellij.singlehotswap (2.3)
    me.shedaniel.architectury (1.6.3)
    izhangzhihao.rainbow.brackets (2023.2.6)
    manifold.ij (2023.1.2)

Kotlin: 231-1.8.20-IJ8109.175
```

**Comment by Lucasmellof** [comment]
Same here

**Comment by DAmNRelentless** [comment]
Now, that I am seeing the changelog, it seems like v2.4 didn't make it to the marketplace. Did you skip it on purpose? The version including this fix seems to be v2.5.

**Comment by LabyStudio** [comment]
The release is still pending for some reason. I don't know why they are taking so long to approve it
